// mảng sản phẩm
const productInLocalStorage = localStorage.getItem("product");
let product;
if(productInLocalStorage != null) // kiêm tra xem localstore có mảng product chưa
{
  product =JSON.parse(localStorage.getItem("product"));
}
else
{
  product = [
  {
    id: "1",
    type: "keyboard",
    name: "ban phim co 69",
    price: "699.000",
    description: "Keyboard for gamer",
    img: "/picture/ban-phim-co-dareu-a98-rgb-04-400x400.jpg",
  },
  {
    id: "2",
    type: "mouse",
    name: "chuot gaming 69",
    description: "Mouse for magaming",
    img: "/picture/mouse.png",
    price: "369.000",
  },
  {
    id: "3",
    type: "keyboard",
    name: "ban phim vjp pro max 69",
    description: "Keyboard for gamer",
    img: "/picture/keyboard.jpg",
    price: "699.000",
  },
  {
    id: "4",
    type: "mousepad",
    name: "lót chuột pro max",
    description: "Mouse pad for wibu ",
    img: "/picture/mousepads.png",
    price: "169.000",
  },
  {
    id: "5",
    type: "speaker",
    name: "loa xập xình",
    description: " loa cho dan choi",
    img: "/picture/speaker.png",
    price: "569.000",
  },
  {
    id: "6",
    type: "mousepad",
    name: "lót chuột siêu vjp pro",
    description: "lot chuot cho dan vjp",
    img: "/picture/mousepads.png",
    price: "569.000",
  },
  {
    id: "7",
    type: "headphone",
    name: "tai nghe vjp pro cho dân quẩy",
    description: "tai nghe hiphop",
    img: "/picture/headphone.png",
    price: "569.000",
  },
  {
    id: "8",
    type: "headphone",
    name: "tai nghe cho người điếc",
    description: "tai nghe magaming",
    img: "/picture/headphone.png",
    price: "569.000",
  },
  {
    id: "9",
    type: "keyboard",
    name: "ban phim co 69",
    price: "699.000",
    description: "Keyboard for gamer",
    img: "/picture/keyboard.jpg",
  },
  {
    id: "10",
    type: "mouse",
    name: "chuot gaming 69",
    description: "Mouse for magaming",
    img: "/picture/mouse.png",
    price: "369.000",
  },
  {
    id: "11",
    type: "keyboard",
    name: "ban phim vjp pro max 69",
    description: "Keyboard for gamer",
    img: "/picture/keyboard.jpg",
    price: "699.000",
  },
  {
    id: "12",
    type: "mousepad",
    name: "lót chuột pro max",
    description: "Mouse pad for wibu ",
    img: "/picture/mousepads.png",
    price: "169.000",
  },
  {
    id: "13",
    type: "speaker",
    name: "loa xập xình",
    description: " loa cho dan choi",
    img: "/picture/speaker.png",
    price: "569.000",
  },
  {
    id: "14",
    type: "mousepad",
    name: "lót chuột siêu vjp pro",
    description: "lot chuot cho dan vjp",
    img: "/picture/mousepads.png",
    price: "569.000",
  },
  {
    id: "15",
    type: "headphone",
    name: "tai nghe vjp pro cho dân quẩy",
    description: "tai nghe hiphop",
    img: "/picture/headphone.png",
    price: "569.000",
  },
  {
    id: "16",
    type: "headphone",
    name: "tai nghe cho người điếc",
    description: "tai nghe magaming",
    img: "/picture/headphone.png",
    price: "569.000",
  },
  {
    id: "17",
    type: "keyboard",
    name: "ban phim vjp pro max 69",
    description: "Keyboard for gamer",
    img: "/picture/keyboard.jpg",
    price: "699.000",
  },
  {
    id: "18",
    type: "mouse",
    name: "chuot gaming 69",
    description: "Mouse for magaming",
    img: "/picture/mouse.png",
    price: "369.000",
  },
  {
    id: "19",
    type: "keyboard",
    name: "ban phim vjp pro max 69",
    description: "Keyboard for gamer",
    img: "/picture/keyboard.jpg",
    price: "699.000",
  },
  {
    id: "20",
    type: "mousepad",
    name: "lót chuột pro max",
    description: "Mouse pad for wibu ",
    img: "/picture/mousepads.png",
    price: "169.000",
  },
  {
    id: "21",
    type: "speaker",
    name: "loa xập xình",
    description: " loa cho dan choi",
    img: "/picture/speaker.png",
    price: "569.000",
  },
  {
    id: "22",
    type: "mousepad",
    name: "lót chuột siêu vjp pro",
    description: "lot chuot cho dan vjp",
    img: "/picture/mousepads.png",
    price: "569.000",
  },
  {
    id: "23",
    type: "headphone",
    name: "tai nghe vjp pro cho dân quẩy",
    description: "tai nghe hiphop",
    img: "/picture/headphone.png",
    price: "569.000",
  },
  {
    id: "24",
    type: "headphone",
    name: "tai nghe cho người điếc",
    description: "tai nghe magaming",
    img: "/picture/headphone.png",
    price: "569.000",
  },
  {
    id: "25",
    type: "keyboard",
    name: "ban phim co 69",
    price: "699.000",
    description: "Keyboard for gamer",
    img: "/picture/keyboard.jpg",
  },
  {
    id: "26",
    type: "mouse",
    name: "chuot gaming 69",
    description: "Mouse for magaming",
    img: "/picture/mouse.png",
    price: "369.000",
  },
  {
    id: "27",
    type: "keyboard",
    name: "ban phim nhu con cac",
    description: "Keyboard for gamer",
    img: "/picture/keyboard.jpg",
    price: "699.000",
  },
  {
    id: "28",
    type: "mousepad",
    name: "lót chuột pro max",
    description: "Mouse pad for wibu ",
    img: "/picture/mousepads.png",
    price: "169.000",
  },
  {
    id: "29",
    type: "speaker",
    name: "loa xập xình",
    description: " loa cho dan choi",
    img: "/picture/speaker.png",
    price: "569.000",
  },
  {
    id: "30",
    type: "mousepad",
    name: "lót chuột siêu vjp pro",
    description: "lot chuot cho dan vjp",
    img: "/picture/mousepads.png",
    price: "569.000",
  },
  {
    id: "31",
    type: "headphone",
    name: "tai nghe vjp pro cho dân quẩy",
    description: "tai nghe hiphop",
    img: "/picture/headphone.png",
    price: "569.000",
  },
  {
    id: "32",
    type: "headphone",
    name: "tai nghe cho người điếc",
    description: "tai nghe magaming",
    img: "/picture/headphone.png",
    price: "569.000",
  },
  {
    id: "33",
    type: "keyboard",
    name: "ban phim du ma js nhu l",
    description: "Keyboard for gamer",
    img: "/picture/keyboard.jpg",
    price: "699.000",
  },
];
localStorage.setItem("product",JSON.stringify(product));
}
